wandb_version: 1

batch_size:
  value: 4
learning_rate:
  value: 3.7769793743176055e-05
lora_alpha:
  value: 32
lora_dropout:
  value: 0.1
lora_r:
  value: 16
max_samples:
  value: 1000
num_epochs:
  value: 3
