wandb_version: 1

batch_size:
  value: 4
learning_rate:
  value: 1.1300319751142629e-05
lora_alpha:
  value: 32
lora_dropout:
  value: 0.1
lora_r:
  value: 8
max_samples:
  value: 1000
num_epochs:
  value: 3
