_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "6": 4.36.2
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
batch_size:
    value: 8
learning_rate:
    value: 2.943961130524373e-05
lora_alpha:
    value: 8
lora_dropout:
    value: 0.2
lora_r:
    value: 8
max_samples:
    value: 1000
num_epochs:
    value: 3
