program: src/scripts/run_sweep.py
method: bayes
name: midi-caption-sweep
metric:
  name: loss
  goal: minimize
parameters:
  batch_size:
    values: [8]
  learning_rate:
    distribution: uniform
    min: 0.00005
    max: 0.0002
  lora_r:
    value: 16
  lora_alpha:
    value: 32
  lora_dropout:
    value: 0.1
  num_epochs:
    value: 5
  max_samples:
    value: 2000
controller:
  type: local
command:
  - ${program}
  - ${args}
early_terminate:
  type: hyperband
  min_iter: 3