wandb_version: 1

batch_size:
  value: 16
learning_rate:
  value: 8.515331443417877e-05
lora_alpha:
  value: 32
lora_dropout:
  value: 0.1
lora_r:
  value: 8
max_samples:
  value: 1000
num_epochs:
  value: 5
