_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
batch_size:
    value: 8
epochs:
    value: 10
learning_rate:
    value: 0.0001
max_samples:
    value: 5000
model:
    value: t5-base
