wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 9.504013359248129e-05
lora_alpha:
  value: 8
lora_dropout:
  value: 0.1
lora_r:
  value: 32
max_samples:
  value: 1000
num_epochs:
  value: 5
