wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 5.182065036130325e-05
lora_alpha:
  value: 16
lora_dropout:
  value: 0.2
lora_r:
  value: 32
max_samples:
  value: 1000
num_epochs:
  value: 3
