wandb_version: 1

batch_size:
  value: 16
learning_rate:
  value: 6.713097902556529e-05
lora_alpha:
  value: 8
lora_dropout:
  value: 0.2
lora_r:
  value: 16
max_samples:
  value: 1000
num_epochs:
  value: 5
