wandb_version: 1

batch_size:
  value: 16
learning_rate:
  value: 2.4464737760431192e-05
lora_alpha:
  value: 8
lora_dropout:
  value: 0.1
lora_r:
  value: 8
max_samples:
  value: 1000
num_epochs:
  value: 5
