wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 2.943961130524373e-05
lora_alpha:
  value: 8
lora_dropout:
  value: 0.2
lora_r:
  value: 8
max_samples:
  value: 1000
num_epochs:
  value: 3
