wandb_version: 1

batch_size:
  value: 4
learning_rate:
  value: 4.516404045197661e-05
lora_alpha:
  value: 16
lora_dropout:
  value: 0.1
lora_r:
  value: 16
max_samples:
  value: 1000
num_epochs:
  value: 5
