wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 6.522914099177017e-05
lora_alpha:
  value: 16
lora_dropout:
  value: 0.1
lora_r:
  value: 8
max_samples:
  value: 500
num_epochs:
  value: 3
