wandb_version: 1

batch_size:
  value: 4
learning_rate:
  value: 5.267482043405139e-05
lora_alpha:
  value: 32
lora_dropout:
  value: 0.1
lora_r:
  value: 32
max_samples:
  value: 1000
num_epochs:
  value: 3
