_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "6": 4.36.2
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
batch_size:
    value: 4
device:
    value: cpu
epochs:
    value: 3
learning_rate:
    value: 2e-05
max_length:
    value: 512
max_samples:
    value: 1000
model:
    value: t5-base
